name: Build and Upload Release Asset

on:
  release:
    types: [created]

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Get version from manifest.json
        id: get_version
        run: echo "VERSION=$(node -p "require('./public/manifest.json').version")" >> $GITHUB_ENV

      - name: Zip dist folder with version
        run: zip -r "netpal-${VERSION}.zip" dist

      - name: Upload netpal.zip to Release
        uses: softprops/action-gh-release@v2
        with:
          files: netpal-${{ env.VERSION }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
